/**
 * Barrel for the primitives. Feature lanes may import either from here or from
 * the individual files — both resolve to the same module instances.
 */
export { Button } from './Button'
export type { ButtonProps, ButtonSize, ButtonVariant } from './Button'
export { IconButton } from './IconButton'
export type { IconButtonProps } from './IconButton'
export { Input } from './Input'
export type { InputProps } from './Input'
export { Textarea } from './Textarea'
export type { TextareaProps } from './Textarea'
export { Select } from './Select'
export type { SelectOption, SelectProps } from './Select'
export { Switch } from './Switch'
export type { SwitchProps } from './Switch'
export { Modal, useFocusTrap } from './Modal'
export type { ModalProps } from './Modal'
export { Sheet } from './Sheet'
export type { SheetProps } from './Sheet'
export { Tooltip } from './Tooltip'
export type { TooltipProps, TooltipSide } from './Tooltip'
export { Popover, PopoverDivider, PopoverItem } from './Popover'
export type { PopoverAlign, PopoverProps } from './Popover'
export { Badge } from './Badge'
export type { BadgeTone } from './Badge'
export { StatusDot } from './StatusDot'
export type { StatusDotProps, StatusState } from './StatusDot'
export { Kbd } from './Kbd'
export { EmptyState } from './EmptyState'
export type { EmptyStateProps } from './EmptyState'
export { Spinner } from './Spinner'
export { Skeleton } from './Skeleton'
export { Toaster } from './Toaster'
export { ConfirmDialog } from './ConfirmDialog'
export { ScrollArea } from './ScrollArea'
export { ACCENT_HEX, BotAvatar, GroupAvatar } from './BotAvatar'
export type { BotAvatarProps } from './BotAvatar'
